// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAki3rQKksJB_lZq16F40o1gn9N7-NxwB0',
    appId: '1:345837181763:android:aa231e43638c3f20106df6',
    messagingSenderId: '345837181763',
    projectId: 'project-elite-a2d57',
    databaseURL: 'https://project-elite-a2d57-default-rtdb.firebaseio.com',
    storageBucket: 'project-elite-a2d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkfH9jGa3yGO-j1-x1W7oHPQcK5apPAE',
    appId: '1:345837181763:ios:a3d291188598f331106df6',
    messagingSenderId: '345837181763',
    projectId: 'project-elite-a2d57',
    databaseURL: 'https://project-elite-a2d57-default-rtdb.firebaseio.com',
    storageBucket: 'project-elite-a2d57.firebasestorage.app',
    androidClientId: '345837181763-h74qs7l4sddskdf0nd1jh0qkktnb7bdm.apps.googleusercontent.com',
    iosClientId: '345837181763-2jod7i44h2esabvuqrbcutj397ni0c5o.apps.googleusercontent.com',
    iosBundleId: 'com.toufiq.elite.projectElite',
  );

}